# Porta do servidor
server.port=8080

# CONFIGURAR SUA SENHA AQUI!
# Banco de dados MySQL
db.url=jdbc:mysql://localhost:3306/sge_flatech
db.username=root
db.password=P@$$w0rd

# Thymeleaf
spring.thymeleaf.cache=false
